---
AWSTemplateFormatVersion: 2010-09-09
Description: 'AWS EMR cluster deployment using Cloudformation'

Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      -
        Label:
          default: "Cluster Configurations"
        Parameters:
          - EMRClusterName
          - Keyname
          - ReleaseLabel
          - MasterInsatanceType
          - CoreInsatanceType
          - NumberofCoreInstances
          - SubnetID
          - LogUri
      -
        Label:
          default: "Applications"
        Parameters:
          - Spark
          - Hive
          - Hadoop
          - Tez
    ParameterLabels:
      EMRClusterName:
        default: "EMR Cluster Name"
      Keyname:
        default: "Key Pair Name"
      ReleaseLabel:
        default: "EMR Cluster Verion"
      MasterInsatanceType:
        default: "Master Instance Type"
      CoreInsatanceType:
        default: "Core  Instance Type"
      NumberofCoreInstances:
        default: "Number of Code Instances"
      SubnetID:
        default: "Subnet ID"
      LogUri:
        default: "S3 locations for Logs"


Parameters:
  EMRClusterName: 
    Description: 'Name of the cluster'
    Type: String

  Keyname: 
    Description: 'Keyname should already be present'
    Type: AWS::EC2::KeyPair::KeyName

  ReleaseLabel:
    Description: 'EMR CLuster Version'
    Type: "String"
    AllowedValues: 
      - emr-5.33.1
      - emr-5.32.1
      - emr-5.31.1
      - emr-5.30.2
      - emr-5.29.0
      - emr-5.28.1
      - emr-5.27.1
      - emr-5.26.0
      - emr-5.25.0
      - emr-5.24.1
      - emr-5.23.1
      - emr-5.22.0
      - emr-5.21.2
      - emr-5.20.1


  MasterInsatanceType:
    Type: String
    Default: 'm5.xlarge'
    AllowedValues: 
      - 'm5.xlarge'
      - 'm5.2xlarge'
      - 'm5.4xlarge'
      - 'm5.8xlarge'

  CoreInsatanceType:
    Type: String
    Default: 'm5.xlarge'
    AllowedValues: 
      - 'm5.xlarge'
      - 'm5.2xlarge'
      - 'm5.4xlarge'
      - 'm5.8xlarge'
      - 'm5.12xlarge'

  NumberofCoreInstances:
    Type: Number
    Default: 1

  SubnetID:
    Type: AWS::EC2::Subnet::Id
    Default: ""

  LogUri:
    Type: String

  Spark:
    Type: String
    Default: 'Yes'
    AllowedValues: 
      - 'Yes'
      - 'No'

  Hive:
    Type: String
    Default: 'No'
    AllowedValues: 
      - 'Yes'
      - 'No'

  Hadoop:
    Type: String
    Default: 'No'
    AllowedValues: 
      - 'Yes'
      - 'No'

  Tez:
    Type: String
    Default: 'No'
    AllowedValues: 
      - 'Yes'
      - 'No'

Conditions: 
  Spark:
    Fn::Equals:
      - Ref: Spark
      - 'Yes'
    
  Hive:
    Fn::Equals:
      - Ref: Hive
      - 'Yes'

  Hadoop:
    Fn::Equals:
      - Ref: Hadoop
      - 'Yes'

  Tez:
    Fn::Equals:
      - Ref: Tez
      - 'Yes'

Resources: 

  EMRCluster:
    Type: AWS::EMR::Cluster
    Properties:
      Applications:
        - Fn::If: 
            - Spark
            - Name: 'Spark'
            - Ref : AWS::NoValue
        - Fn::If: 
            - Hive
            - Name: 'Hive'
            - Ref : AWS::NoValue
        - Fn::If: 
            - Hadoop
            - Name: 'Hadoop'
            - Ref : AWS::NoValue
        - Fn::If: 
            - Tez
            - Name: 'Tez'
            - Ref : AWS::NoValue

      Instances:
        Ec2KeyName:
          Ref: Keyname
        Ec2SubnetId:
          Ref: SubnetID
        MasterInstanceGroup:
          InstanceCount: 1
          InstanceType: 
            Ref: MasterInsatanceType
          Market: ON_Demand
          Name: Master
        CoreInstanceGroup:
          InstanceCount:
            Ref: NumberofCoreInstances
          InstanceType:
            Ref: CoreInsatanceType
          Market: ON_Demand
          Name: Core
        TerminationProtected: false
      
      ReleaseLabel:
        Ref: ReleaseLabel

      Name: 
        Ref: EMRClusterName

      AutoScalingRole: EMR_AutoScaling_DefaultRole

      ServiceRole: 
        Ref: EMRClusterServiceRole
      JobFlowRole:
        Ref: EMRClusterinstanceProfile

      LogUri:
        Ref: LogUri

      VisibleToAllUsers: true
  

  EMRClusterServiceRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Principal:
            Service:
            - elasticmapreduce.amazonaws.com
          Action:
          - sts:AssumeRole
      ManagedPolicyArns:
      - arn:aws:iam::aws:policy/service-role/AmazonElasticMapReduceRole
      Path: "/"

  EMRClusterinstanceProfileRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Principal:
            Service:
            - ec2.amazonaws.com
          Action:
          - sts:AssumeRole
      ManagedPolicyArns:
      - arn:aws:iam::aws:policy/service-role/AmazonElasticMapReduceforEC2Role
      Path: "/"
  
  EMRClusterinstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Path: "/"
      Roles:
      - Ref: EMRClusterinstanceProfileRole

